### PR TITLE
20151123 multiline proto parsing

### PR DESCRIPTION
**Pull request by codebybrett**
Supports multiline function prototypes which may include arbitrary embedded comments.

Also adds parsing of function identifiers.

Uses C preprocessing token lexical parser, but only uses part of it.  As the preprocessing token lexical parser is not large, it seemed a better idea to just include it in case of future use, rather than inline bits of it.

### CODE REVIEW

**Comment by codebybrett** [comment]
Realised Format2012 parser should not have new multiline proto parsing enabled. I think this completes the change.

**Comment by hostilefork** [comment]
Format2012 is not coming back, so it can go!

**Comment by codebybrett** [comment]
I'd left Form2012 in case @earl had some outstanding changes, but it's getting late for that, so ok, I've removed it.

Test PR is waiting on this one.

**Comment by hostilefork** [comment]
Sorry to hold you up.  Being buried alive and fighting it full time for a bit but stopped to pick up dev again today... hopefully going to pick up for some lost time.

Gave a pathological test just to see what was handled:

    /* inline before */ struct Reb_Call *Make_Call( // end of line after
        // Single line before
        REBVAL *out,

        REBSER *block, // end of line after

        REBCNT index, /* multi-line
        inline after */

        // Multi line end of line
        // before
        const REBVAL *label, const REBVAL *func
    /* more stuff */ // just testing
    ) /* to see */ { /* what might */ // trip up

Most of which I don't really care about, but it seemed that the simple case isn't working for me:

    struct Reb_Call *Make_Call(
        REBVAL *out,
        REBSER *block,
        REBCNT index,
        const REBVAL *label,
        const REBVAL *func
    ) {

In tmp-funcs.h I get:

    extern struct Reb_Call *Make_Call(; // m-stacks.c

Does that case work for you?

**Comment by codebybrett** [comment]
The second case works for me.  In the first case, I have not allowed white-space (including comments) at the beginning of the line of the function proto, so that case fails as written.

I tested using both ren-c as built and a rebolsource build for r3-make. I tried again after removing and re-cloning my local Ren-c and had no problems.

The first case works "struct" starts the line. As I haven't bothered with stripping white-space from tmp-funcs.h output this is the result:

    extern struct Reb_Call *Make_Call( // end of line after
    // Single line before
    REBVAL *out,

    REBSER *block, // end of line after

    REBCNT index, /* multi-line
    inline after */

    // Multi line end of line
    // before
    const REBVAL *label, const REBVAL *func
    /* more stuff */ // just testing
    ); // m-stacks.c

The reason I disallowed white-space (including comments) at the beginning of the line was that it was a simple way to prevent the parser matching on source that is not part of the function declarations.

Don't know why it is not working for you.

**Comment by hostilefork** [comment]
Can you commit the second change and see if Travis passes it?

**Comment by codebybrett** [comment]
Travis appears to be fine with it.

**Comment by hostilefork** [comment]
I think this was user error on my part I think I must have accidentally clicked the wrong branch of yours!  Your names are long and similar looking...perhaps part of the problem with those long numeric prefixes when corresponding a name out of the PR with the name in a tree view...

Rebased and merged as daecfb1 !

**Pull request closed without merging**
