### PR TITLE
Minor changes for OSX compilation + VIM users

### PR DESCRIPTION
**Pull request by draegtun**
As promised those hefty changes all wrapped up for you!  (oh sneaked in a little Vim .gitignore which should be handy)

### CODE REVIEW

**Comment by hostilefork** [comment]
Well in the spirit of us following best practices, and getting in the rhythm of seeing Rebol improving every day... :-) how about we break this into two PRs to deal with separately.

@rgchris brought up the question of what a "good" project .gitignore looks like on the whole.  So that's a research topic, and one whose summary could be up top at the .gitignore file itself.  The PR would thus be "new .gitignore strategy" or something.

If you haven't had practice with amending commits, that's another thing.  I've gotten pretty good at `rebase -i` now and can say it's quite useful.  So how about breaking this one in place (w/o a new PR) for the #include ... I'll take that, and then a new one about .gitignore (even if it's just a comment at the top of the .gitignore file)

**Comment by draegtun** [comment]
Done.

For .gitignore strategy see this - https://help.github.com/articles/ignoring-files/

I've created my own ~/.gitignore_global file with necessary VIM (and Mac) exclusions.

I'll start a new PR for .gitignore strategy.

**Comment by hostilefork** [comment]
Note for workflow the point I was trying to raise about PRs.  Namely that this is two commits, and it would be nice if it were just one.

When you have a commit you want to just touch up, and it's the last commit you've done, you can `git add` your files like you were going to do an ordinary commit.  Then `git commit --amend`.  You can edit the description as well if you do this.

*(Of course, this will change the hash...and any commits down the chain which build on your commit will be screwed.  But a PR is generally understood to be a "work in progress" where such things might happen and you deal with the consequences.)*

The goal is to have as clear a version history as possible, so people doing a "git blame" or otherwise don't have to sort out any more churn than necessary.  e.g. we'd like to see this as just one commit that changes the include when I merge it, not two.  I've learned a bit about this lately after procrastinating on doing so, hence forgive me for telling you something if you already know... but it's actually rather straightforward and I'll point to this for other committers too.

The thing to try here would be `git rebase -i` now ('-i' meaning interactive).  If you're on this branch you should be able to say `git rebase -i HEAD~2` (just consider the last 2 commits) and it will look like:

    pick f39a111 Minor changes for OSX compilation + VIM users
    pick 588acb1 Removed VIM .gitignore changes

    # Rebase 0f25855..588acb1 onto 0f25855
    # ... (more comments from git, all lines with # are ignored) ...

You can do lots of things with this; if you delete a line it will rewrite history and that commit goes goodbye.  You can reorder the lines to put the commits in other orders.  And what I'd like you to try would be to change the second `pick` into a `squash` so that it creates one new commit out of the two.  A "squash" line must always have a non-squashed commit in front of it, so you couldn't squash the first commit here as there's nothing listed to squash it into.

Once you change the pick into a squash and save, git will do it and come up with an opportunity for you to rename the new commit from all the ones you squashed together.  Their comments will be in the editor for you to rewrite.  So you could squash them and rename to "change include of malloc.h to stdlib.h".  Note the conventions for git comments here:

    http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

I see you're basing your .gitignore on this change and building forward from it.  But what you really want to do with patches is go back to master and branch off from it *unless* the subsequent change is dependent.  The gitignore changes aren't dependent so you don't want this commit as a parent.

Just trying to set the stage for a growth model here where everyone's doing it "the way you're supposed to".  And it's easiest to start getting that right with these tiny commits that you can just as easily copy the file and paste it and do it again if you must...

I need to switch this over to [git-flow](http://nvie.com/posts/a-successful-git-branching-model/), also...and add a develop branch, and get all that going properly... lots to do!

**Comment by hostilefork** [comment]
*(P.S. if you don't have [SourceTree](https://www.sourcetreeapp.com/), it can be a nice way of looking at things.  Does some goofy stuff but useful.)*

**Comment by draegtun** [comment]
Yes I accidentally started the gitignore PR on wrong branch :(     Unfortunately it got Github's knickers in the twist.   So tried to resolve by mixture of rebase/reverting/delete that branch which at least made my fork on Github happier but causing me extra headaches elsewhere :(

Anyway I've squashed the commits for OSX patch.   However you can see now that my reverts have appeared here (it wouldn't let me push OSX-patch-1 changes without pulling in master).

So still not pretty so may require further triage.

**Comment by hostilefork** [comment]
Heh.. yup now you've got [6 commits](https://github.com/metaeducation/ren-c/pull/13/commits) including a merge of master... :-)  Things definitely git confused!

Let's try starting from the top on this one, but not give up and go to a new branch or starting commit.  I'll save what you've written on the .gitignore here just in case something goes awry:

## .gitignore strategy
#
# Only keep ren-c project specific file exclusions in .gitignore
#
# For files created by... 
#
#   * Editors (for eg. Vim, Eclipse, etc) 
#   * Machines (Windows, Linux, OSX, etc)
#   * or any artifacts of your development environment
#
# then please keep these exclusions in a global .gitignore file which
# should not be commited into the ren-c repo.
#
# For more info please see "Create a global .gitignore" at:
#
#     https://help.github.com/articles/ignoring-files/
#
# Our recommended advice is to use a .gitignore_global file described
# in link.
#           
# Here is an example .gitignore_global used on OS X (Mac):
#     
#      ## Mac stuff
#      .DS_Store
#  
#      ## Vim stuff
#      *.un~
#      *.swp
#
# This is kept in the users home directory:  ~/.gitignore_global
#

Now that we're safe...

Since all we're doing here is changing one #include, start by putting yourself on the branch and making sure you don't have any local changes to tracked files that you care about:

     git stash
     git checkout OSX-patch-1

Now let's get back to the state of that first commit.

     git reset --hard f39a111b2b24898e4bfbf1e6e9fac6c64feebd7f

*(If you haven't noticed, you can [abbreviate the hashes](f39a111b2b24898e4bfbf1e6e9fac6c64feebd7f).)*

There are a few ways you can go from here.  You could reset one commit back, but do so "soft" so that the changes in that commit come back to your staging area.

    git reset --soft HEAD~1

So this will put you back in time to the moment before your commit, so you can discard the .gitignore changes and only add the #include change.  Then you commit again.

Or you could undo the change by hand, add it to the staging area, and then do `git commit --amend`.  This does an effective squash of new changes into the last commit you've made.

Or you could try again to make another commit entirely so you go back to having two, then try to `rebase -i HEAD~2` and get things squashed down into one commit.

But no matter what you do, you've pushed stuff on the branch 'OSX-patch-1' that made it to your hosted repo on github.  And github requires you to push with --force to rewrite any pushed change.

    `git push origin OSX-patch-1 --force`

Anyway, just some hints on how to get out of the 6-commit situation!  Feel free to ask questions; I don't know everything but I know more than I did before I tried this gigantic merge/unfork/coherence...

**Comment by draegtun** [comment]
Many thanks for info.   I was just starting the same hard reset when I saw your comment.  I was looking at getting my forked repo back to a saner state before apply patches again.

Anyway I took your --soft HEAD~1 route so patch is now in order.   Just going to clean up my repo before doing gitignore PR!! (like you I already kept a copy of those changes!)

Onwards & upwards

**Comment by hostilefork** [comment]
Great!  Yup, I held off a while on getting used to the mechanics of `git` and really learning how to rebase and merge and do all of it.  I understood the theory but it seemed to easy to have all the branches crossing sideways and not knowing what was going on.  Now I can pretty much do it.  *(Still get into weird situations sometimes and have to dig myself out, not knowing quite where I went wrong though...)*

So if we keep the engine going and people learn and contribute and see progress, who knows... it just might get traction...

**Pull request merged**
