### PR TITLE
Create docs/ for use in Github Pages

### PR DESCRIPTION
**Pull request by giuliolunati**
place there all replpad-js stuff
NB there is not and index.html
use replpad.html or template.html instead

### CODE REVIEW

**Comment by hostilefork** [comment]
I have wondered if a parts of the ReplPad that should be in the JavaScript extension.  For instance, the JavaScript READ, JS-DO, CSS-DO, etc.

Then, I have wondered if there are parts of the ReplPad that should be in a "terminal" extension (to provide INPUT and WRITE-STDOUT).

Both of these would have to take for granted some amount of JS code, CSS, maybe HTML.

But I don't know that it's time to be doing this yet, so I don't think the ReplPad code (e.g. gui.js) should be moved into the main repository at this time.

**Comment by giuliolunati** [comment]
@hostilefork my intent is to host replpad-js in docs/ of main ren-c repository, and eventually serve it at Github Pages

**Comment by hostilefork** [comment]
> my intent is to host replpad-js in docs/ of main ren-c repository, and eventually serve it at Github Pages

I want you to have the freedom to do what experiments you need to get the loader in order.  But if you want to do something like this, please do it with a `git clone --depth=1` on Travis, or otherwise pulling replpad from where it lives, vs. making another copy in the repo...

**Comment by hostilefork** [comment]
If you have to serve the replpad from GitHub for what you are doing, then perhaps a submodule can do that?

https://git-scm.com/book/en/v2/Git-Tools-Submodules

Though I'd really like the loader to be pulling everything it needs from S3, not GitHub

**Comment by giuliolunati** [comment]
Ok, I understand. And if we host in docs/ only the load-r3.js stuff and activate Github Pages only for testing purposes, that's fine for you?

**Comment by hostilefork** [comment]
> Ok, I understand. And if we host in docs/ only the load-r3.js stuff and activate Github Pages only for testing purposes, that's fine for you?

Activating GitHub pages is fine.  I don't care how things are organized just yet, so long as every file is just in one place!  :-)

**Pull request merged**
