### PR TITLE
Non-bounded SKIP/ONLY, NEXT+BACK don't clip (yield blank)

### PR DESCRIPTION
**Pull request by hostilefork**
SKIP and AT have historically clipped their skipping at the head and
tail of the series, e.g.

    >> skip "abcd" -100
    == "abcd"

While arguably useful, it's not always the intent.  This adds an /ONLY
refinement that does not bound in this way, but returns blank if it
tries to go past the bounds:

    >> skip/only "abcd" -100
    == _

The NEXT and BACK specializations (skip offset +1 and -1 respectively)
are then modified to use this invariant, as it is less likely to
obscure bugs...and can make tests for TAIL? or HEAD? unnecessary:

    while [pos: next pos] [
        ...
    ]

If one truly needs the previous bounding behavior, SKIP without /ONLY
can be used with 1 or -1 respectively.

This also revises the treatment of LOGIC! with SKIP, such that it
presumes TRUE means act like NEXT, while FALSE means return the series
at its current position.

    >> skip "abc" true
    == "bc"

    >> skip "abc" false
    == "abc"

### CODE REVIEW

**Comment by hostilefork** [comment]
This commit is an attempt to make NEXT and BACK less error prone, so that **next next back back** either gets you back where you started, or makes some kind of noise.  I also believe it makes them more practical by saving on TAIL? or HEAD? checks in some scenarios.

But it seemed to me from looking around that changing baseline SKIP would be too disruptive.  In general, Rebol has the idea that if you provide some kind of /PART it doesn't error if you go past things.

    >> copy/part "abc" 100

Changing SKIP would suggest a sort of systemic change on things of that type, and who knows what all that would mess with.  But I think NEXT and BACK are special cases that benefit from heeding the "one unit" or giving you some kind of feedback that it couldn't.

As evidence that it's not terribly disruptive, there were only two cases in the process of mezzanine and bootstrap that needed to be adjusted.

* One was a bug.  It did `new-line back spec true` when the spec was always at the head position, and it should have just said `new-line spec true`. 

* The other was the implementation of LAST which was trying to give `first back tail series` of a potentially empty series.  FIRST doesn't accept BLANK! (and probably should not).  `pick series length of series` is another way of addressing it without a temporary variable.

With a decision like this, it triggers questions on what routines should tolerate blanks as input and give blanks as output.  (what was called "none propagation")  I notice that Rebol2 did not allow NONE! as an input to either PICK or SELECT, while R3-Alpha and Red allow it for SELECT and not PICK.  As I say, it seems to me that FIRST taking BLANK! and not erroring is more dangerous than useful... so that suggests PICK with 1 falls in the same category.  I don't know what would make SELECT special.

It's all worth thinking over, but I'm curious if anyone has any cases on this topic to speak up for...

**Comment by codebybrett** [comment]
Looks useful.

**Comment by hostilefork** [comment]
Merged and rebased as:

https://github.com/metaeducation/ren-c/commit/9abff58c67eb56cd30c68318bcdbd0d8699ad07c

The shorthands are getting pretty good, as it can now be used with things like OR:

    series: my next or (fail "didn't expect end of series")

Which would be a shorter way of a shorter way of writing:

    series: next series
    if tail? series [fail "didn't expect end of series"]
    series

And don't forget WAS, where you get:

    was series: my next or (fail "didn't expect end of series")

...as a shorter way of writing R3-Alpha's:

    also series (
        series: next series
        if tail? series [fail "didn't expect end of series"]
    )

Fancy...

**Comment by codebybrett** [comment]
Fancy indeed.

**Pull request closed without merging**
