### PR TITLE
20151015 new source scanner

### PR DESCRIPTION
**Pull request by codebybrett**

### CODE REVIEW

**Comment by hostilefork** [comment]
Can confirm that this works now!

*(We'll probably want to lighten up the logging by default so it's not quite so chatty.)*

I'll look over the source and make some notes.

**Comment by codebybrett** [comment]
Might be a false positive.

I was working with @rgchris to see if his system would replicate the problem you had. Last we'd got to was an invalid notes string for proto "static void str_to_char(" (%core/t-string.c) in make/data/file-analysis.reb. There's a comment that makes the parser thinks it's the new format when it is not. But on my system that's not an issue. On Chris' system the notes string is invalid (unterminated).

As the file is created with SAVE, there might be a bug in SAVE for A111.

The log chattyness is due to bug finding.

**Comment by hostilefork** [comment]
Hm, well tripping over a Rebol bug in the old interpreter is not that unlikely, there are lots of them.

But it is working for me here, and it's working for Travis.  So Chris's build on mac, now?

**Comment by codebybrett** [comment]
It builds on Chris' Mac Snow Leopard with a "regular OS X 32-bit build" from rebolsource as r3-make.

If Chris uses A111 from rebol.com/r3/downloads then it fails because that r3 for that platform is pretty horribly broken as in:

    >> next "abc"
    == "^@^

    >> mold next "abc"
    == {"^^@^^}

which presumably are what cause:

    >> load-until-blank { !!! "STRING value to CHAR value (save some code space)" <-- what?^/}
    == [[!!! "STRING value to CHAR value (save some code space)"] "^@?Ü?^@^_^@

I see no point in trying to workaround such brokenness.

**Comment by hostilefork** [comment]
> I see no point in trying to workaround such brokenness.

I understand how you feel.  But if it's possible to put aside the feeling and make a workaround I would argue it does have a point in general...

Though this does sound pretty narrow.  If it's really just the mac build under A111 we can just put a caveat and say that doesn't work.  If the rebolsource build works and other platforms work from the rebol.com old download then I say we're good.

**Comment by hostilefork** [comment]
Phrased more clearly *"I think that it's okay if it's just that, and we can let it go...although if it is just a small change to hack around it such that it works, we might should make the small change...even if it feels annoying to make the change."*

**Comment by codebybrett** [comment]
Ok. So for the record:

* Travis is using A111 on Linux from the old rebol.com downloads and passing with the trailing folder slash workaround.
* The same on Snow Leopard does not build due to the bug described above.
* A111 for windows from the old rebol.com downloads crashes and was flagged by my anti-virus program.
* Using a rebolsource build on Snow Leopard and Win 7 works.
* The rebolsource build (for windows at least) doesn't need the trailing folder slash workaround (which is implemented by "fixed-source-paths" in rebol-c-source.reb).

I'll leave it to you to write the caveat regarding A111 on Snow Leopard and perhaps Windows.

**Comment by hostilefork** [comment]
Wondering out loud, and not saying you have to do this yourself if you don't want to.  But how much change do you think it would take to modify the old make-make process to *minimally* accept the new source format?

It seems to me that we've sort of got a "trick" to the pattern, in that you can look for comment blocks that use two spaces to get to their first content.  Then you have your loader that progressively looks at the lines as long as they stay valid Rebol code.  Then text commentary.

The next issue of grabbing prototypes could be to get everything from when the comment ends to the opening brace.  Lose any comments from that, strip down spaces.

If we "thought like that" then how few and relatively self-contained files could that functionality be grafted in on the current bootstrap, keeping it minimal?  Could the rest of it (source analyzer and converter) be isolated perhaps as a part of the test module... so if there are additional rules checked we check them there, as opposed to the bootstrap depending on it?

I'd really like to move on the source conversion and tab conversion as soon as we can.  But looking through it I am finding myself thinking through the potential consequences of the "small files replaced with oodles of code".  So trying a really simple patch for accepting the new format seems it would be prudent, and maybe we break the analyzer off into tests.

**Comment by codebybrett** [comment]
make-header.r,  make-os-ext.r, make-reb-lib.r are the ones that search for prototypes I believe.

At mimimum the change should also include some refactoring of the old scripts relevent to the changed sections as some parts of them are extremely poor, e.g. variable naming.  Probably also, the change should utilise the preprocessing token lexical definitions.

The source conversion script is not part of this pull request, it's an older script and I'm considering it as a one off.

I don't know whether  "*minimally* accept the new format" means to accepts the new format at the same time as accepting the old format or as a replacement for accepting the old format. Perhaps it doesn't matter.

**Comment by codebybrett** [comment]
Closing request in favour of a simpler strategy.

**Pull request closed without merging**
