### PR TITLE
FEAT: basic support for ANSI escape sequences in Windows console

### PR DESCRIPTION
**Pull request by Oldes**

### CODE REVIEW

**Comment by hostilefork** [comment]
Always good to see contributions.

What I've been wanting to see is a better abstracted **console://** port of some kind.  Then the REPL would be hooking that, and getting notifications about keypresses and such.  The notifications need to be rich enough to get up/down cursor presses to implement the history in usermode.  You have noticed here that we're trying to put more and more behavior in usermode...here's @draegtun's notes on his skinning:

https://github.com/r3n/reboldocs/wiki/User-and-Console

So I feel what we need here is to establish what that protocol is by which color is requested of the console.  I don't think speaking in ANSI control codes is very literate, e.g. when it used to say:
		  
    HELP    - For starting information

It feels a step backwards from coherence to see:

    ^[[1;33;49mHELP    ^[[0m- For starting information

So however the usermode code makes requests of the **console://**, I think we probably want to step outside the realm of strings to accomplish those requests.  I don't know what it should look like, but more like:

    write console:// [<bold> {HELP} </bold> space {- For starting information}]

Obviously, some C code is going to need to be backing that, so we have to have some code *like* what you have written.  But we also have to consider more than just Windows.

There have been console requests, such as being able to "pre-load" text into the input buffer...which is a feature needed to implement command history in userspace (where it should be) as well.  I'm interested in having more people involved in the design.  I don't know that we want to throw in a single feature on a single platform without greater consideration though.

**Comment by hostilefork** [comment]
All that said: since you've written code, if you want the feature included for your own use on Windows, and plan to stick around and work on things...it probably wouldn't hurt.  We just won't put usages of it in the default console: it would be something you'd have to use in your own custom skin.  And you would have to accept that if it got in the way of other work, it might be axed.

**Comment by hostilefork** [comment]
Well, I tried.

But you've submitted a PR with no commentary on your motivations or concerns, in code with no comments, on a feature no one asked for, on a single platform, deliberately taking readable source and making it unreadable, and you didn't react to the Travis CI breakage.  In the meantime, serious issues hang in the balance which we are working on, that I'll wager you are incapable of fathoming.

It continues a pattern of your behavior I find unacceptable.  But hey--we're all different--so let's agree to disagree.  And as I said, there's a place for you.  It's called Red.  Please go back there.  Thanks.

**Comment by Oldes** [comment]
The motivation is to be able use ANSI color sequences, which are by default supported in non Windows systems and don't worry, that on Windows it would look unreadable.

image

The code in HELP was there just as an example, you could wrap it in whatever else... easily define sequences as variables and use rejoin.. whatever.. but if you don't want it, I have no problem with it. It is your right.

**Comment by hostilefork** [comment]
It may be useful in the future, thanks.

**Pull request closed without merging**
