### PR TITLE
Bash script to download from S3 prebuilt binaries for compiling ren-c

### PR DESCRIPTION
**Pull request by lkppo**

### CODE REVIEW

**Comment by hostilefork** [comment]
Looks like a great start!!

Regarding the name, I'd like to keep the number of scripts at a minimum...so what I was envisioning was that it would be %make.sh ... and it would do everything it could to get you to a finished build if it could.  

This means it would not repeat work it thought it had already done.  So perhaps the second time you run it, it could check for something it put in the prebuilt directory the first time.

I'm actually in travel mode right now, so I can't easily look at too many things for the next week or two.  @giuliolunati, could you take over advising and maybe figuring out how we do this?

@draegtun - I seem to remember you as being on mac, for some reason?  If so, can you check that?

@gchiu can test whatever %make.bat variation if one comes up--a technique like this might be best for "lowest common denominator"?

https://superuser.com/a/373068

**Comment by lkppo** [comment]
I have renamed it make.sh, but I am hesitant with this idea because it means that this script becomes an envelope and must reflect all the build options. Yet this script can not work on Windows natively without cygwin. What would give two scripts with all the options? I can easily program a vbscript or a powershell for a complete build with msvc but my build chain is not ready for this case.

If there are 3 or 4 options it's ok, assuming the config files are ready for the desired target.

**Comment by lkppo** [comment]
> This means it would not repeat work it thought it had already done. So perhaps the second time you run it, it could check for something it put in the prebuilt directory the first time.

Ok, I will do this point.

**Comment by draegtun** [comment]
Tested on Mac (which has `curl` but not `wget`) and came across 3 issues....

* Bug when checking for curl binary

* Sed part only returned first file from XML

* `-f` switch (in `chmod`) needs to be before mode settings

Below is a patch which fixes both above.  Also I changed S3 URL because Amazon are [phasing out path-based  URLs](https://forums.aws.amazon.com/ann.jspa?annID=6776)

BTW - I used Perl instead of Sed because it was quicker for me to fix issue. Perl should be everywhere Sed is!


    --- orig.make.sh    2019-05-12 14:02:12.000000000 +0100
    +++ make.sh 2019-05-12 14:03:24.000000000 +0100
    @@ -19,7 +19,7 @@
     if [ $? -eq 0 ] ; then
         dltool="wget"
     else
    -    which curl /dev/null
    +    which curl > /dev/null
         if [ $? -eq 0 ] ; then
             dltool="curl"
         else
    @@ -30,7 +30,7 @@
    
     echo ""
     echo "Get the list of available prebuilt binaries from S3"
    -s3url=https://s3.amazonaws.com/r3bootstraps/
    +s3url=https://r3bootstraps.s3.amazonaws.com/
    
     if [ $dltool = "wget" ] ; then
         xml=$(wget -q $s3url -O -)
    @@ -38,8 +38,9 @@
         xml=$(curl -s $s3url)
     fi
    
    -pblist=$(echo "$xml" | sed -e 's/<\/Key>/<\/Key>\n/g' | sed -n -e 's/.*<Key>\(.*\)<\/Key>.*/\1/p')
    -
    +pblist=$(echo "$xml" | perl -nle '@f = $_ =~  m{<Key>([^<]+)}g; for (@f) {print "$_\n"}')
    +
    +
    
     echo ""
     echo "Download prebuilt binaries"
    @@ -61,7 +62,7 @@
    
     echo ""
     echo "Make executable prebuilt binaries"
    -chmod +x -f r3-*
    +chmod -f +x r3-*
    
    
     echo ""

**Comment by draegtun** [comment]
> Regarding the name, I'd like to keep the number of scripts at a minimum...so what I was envisioning was that it would be %make.sh ... and it would do everything it could to get you to a finished build if it could.

I wonder if this script should be called (something like) `get-binaries.sh` and kept in the `prebuilt/` directory?

**Comment by lkppo** [comment]
Thanks draegtun.

I made all changes except sed => Perl because I don't know if Perl is installed by default on  cygwin.

Will check that, or we can find an alternative in sed or awk.

For the name, we need to know if this script is only for donwloading binaries or if I expand it to be a %make.r wrapper.

**Comment by lkppo** [comment]
Is perl installed by default on mac?

**Comment by draegtun** [comment]
> Is perl installed by default on mac?

Yes its standard on MacOS.   

re: Windows - Yes like you say I'm not sure about Cygwin having Perl so that would need testing.

**Comment by lkppo** [comment]
The last week I check that. OpenBSD has also Perl by default, so a native perl script could be a better solution.

**Comment by hostilefork** [comment]
> I have renamed it make.sh, but I am hesitant with this idea because it means that this script becomes an envelope and must reflect all the build options.

Can the script just pass through the build options it gets to make.reb?

**Comment by lkppo** [comment]
Ok, I modified the script to pass the arguments to make.r without any other form of ceremony. OSs compatible with precompiled binaries are detected to start the compilation with the correct binary. Tested on Windows and OpenBSD.

A second script test.sh allows to run the tests without effort.

**Comment by giuliolunati** [comment]
And, I dislike the use of Perl. I don't want to install it on my phone.

**Comment by lkppo** [comment]
uname -o doesn't exist on BSD. uname -o could be a refinement of -s detection

I used https://en.wikipedia.org/wiki/Uname as reference knowing the android case is false at this point.

**Comment by lkppo** [comment]
uname -o doesn't exist on BSD. uname -o could be a refinement of -s detection

I used https://en.wikipedia.org/wiki/Uname as reference knowing the android case is false at this point.

**Comment by giuliolunati** [comment]
@lkppo you could substitute perl filter with `echo $xml |sed 's=<Key>=\n=g'|sed 's=</Key>.*=='`

**Comment by lkppo** [comment]
Ok will try that tonight.

**Comment by lkppo** [comment]
See above the remark of draegtun. Your code does not work because "\ n" is not recognized under mac / bsd. I want to look for a solution in pure sed / awk, there is but for the moment I have not managed to implement them.

**Comment by lkppo** [comment]
@giuliolunati Problem solved.

**Comment by giuliolunati** [comment]
So we are ready to merge?

**Comment by lkppo** [comment]
Yes, I think it's of ok, unless you want to make the version .bat for windows right now.

**Comment by giuliolunati** [comment]
Merged :-)

**Comment by lkppo** [comment]
Thank you.

**Comment by hostilefork** [comment]
Cool stuff, thanks @lkppo -- and to @giuliolunati and @draegtun for looking over it while my availability is limited as I focus on conference-stuff!

I'll be trying to catch up on the backlog this week.  Bit of feedback here:

* Documentation on why the file exists at the top of the file itself is always helpful (e.g. bringing people up to speed on what they're looking at).  I'll do that at some point if no one else does.

* Project standards are 80 column lines, no whitespace at end of lines... so it's good to configure editors to have that 80 column margin line, and clean up whitespace on save.

* RE: `%test.sh` - the root directory of a project is kind of "prime real estate" and you want to try to keep it focused.  So I'm not sure if people running the tests is something that needs an automation entry point in the project root?   If this is to be kept, it should be moved to `%tests/`.  Also, the name sounds a bit like a name for a file that I might create as a temporary file (almost like `temp.sh`)...I wondered if it was a temp file I'd made until I looked at it.  So perhaps it should be `run-tests.sh`?

* There's no urgency from me on having a Windows version of the script.  But when there is, I would like it to have he same kind of sensitivity shown in this PR discussion to "what's around by default".  To me that looks like using PowerShell's download features if powershell is available, or falling back to [BitsAdmin](https://superuser.com/questions/25538/how-to-download-files-from-command-line-in-windows-like-wget-or-curl/373068#373068) if not.

Really no rush on anything; pretty much everything not conference-related can wait until after 4 July!

**Comment by lkppo** [comment]
I will care of three first points in a new PR. For the windows script I will do it in another one. If I can I prefer to avoid the horrors of .bat. One thing that annoys me with Powershell is that you have to activate it because it is blocked by default for security (what irony) but since we are talking to developers there is no reason they be scared by typing one command before the first run (a note in the README should be enough).

**Pull request merged**
