### PR TITLE
Add hook points: DECLARE_LOCAL and Move_Value()

### PR DESCRIPTION
**Pull request by hostilefork**
This changes what used to look like:

     void Foo(REBVAL *src) {
          REBVAL dest;

          dest = *src;

          DoSomeStuffWith(&dest);
          DoSomeMoreStuffWith(&dest);
     }

into

     void Foo(REBVAL *src) {
          DECLARE_LOCAL (dest);

          Move_Value(dest, src);

          DoSomeStuffWith(dest);
          DoSomeMoreStuffWith(dest);
      }

Though slightly more verbose, it isn't uglier...and arguably, the symmetry with stack-based locals and other REBVAL being talked about by pointer makes it better.

But the real motivation was to be able to inject code at the point of declaration and at the point of assignment.  The DECLARE_LOCAL permits the ability to mark stack slots as being such, so that if an attempt to move a value containing some "non-reified" stack material into that slot is made, it can decide whether it's safe to leave the material non-reified or if it has to create GC-able objects first.

The primary hope of this is to help with avoiding the reification of REBFRM* into GC'd objects--and to build on that success to permit so-called "virtual binding".  However, as a generic debug hook, it's very helpful to be able to inject code at these points...to catch problems at the site of initialization or copying of a value.

### CODE REVIEW

**Comment by hostilefork** [comment]
@ShixinZeng This change obviously affects a lot of files.  But I have to say, I surprisingly think it came out as an improvement.  And it's good for adding more debugging features--which wasn't even the intent.

Also it means the C debug build gets checks that were formerly only being done in the C++ debug build.

I quickly warmed up to this, despite dreading it from the old days of [VAL_INIT_WRITABLE_DEBUG](https://github.com/zsx/r3/issues/31#issuecomment-222518268).

I can't say for sure yet if the trick I have in mind is going to do what I want it to.  But even if it did not, I think this is a useful change.

**Comment by zsx** [comment]
Interesting ideas. I think the ultimate goal for these changes is to avoid unnecessary reification of frames, i.e. only reify a frame if any of its arguments is copied out and outlives the function call, right? DECLARE_LOCAL only marks the C locals, so when a C local REBVAL will become an argument of a Rebol function, through Apply_Only_Throw?

**Comment by hostilefork** [comment]
> I think the ultimate goal for these changes is to avoid unnecessary reification of frames, i.e. only reify a frame if any of its arguments is copied out and outlives the function call, right?

That's actually just the near term goal.  :-/  The real goal is a generalized solution by which non-GC state relevant to values can avoid reification...and I'm thinking especially about these new classes of "derived specifiers", e.g. for "virtual binding".

>  so when a C local REBVAL will become an argument of a Rebol function, through Apply_Only_Throw?

My strategy is that if something is marked with VALUE_FLAG_STACK, then *when and if* you have an un-reified value that is being stored, it walks *backward* in REBVAL size steps until it finds a properly marked FRAME!.

This means such a scan will be slower on function arguments, which will have to step backwards until they find the canon FRAME!.  But still, it should only be O(N/2) steps in what should be a pretty fast scan, locality-wise.  Those kinds of things are a lot faster than stack walking through linked list pointers.  If you haven't read this:

http://blog.hostilefork.com/locality-locality-locality/

Moreover, if there's ever a miss and it has to reify, it will rewrite both source and destination.  So once it pays, it won't keep having to scan to see if it needs to pay again.

Requires a bit of rewiring, to say the least.  But like I say, even if all this turns out to be a pipe dream and doesn't work, I think this particular source change still a win for its debug-build merit.  And you can [look at the diff](https://github.com/metaeducation/ren-c/pull/403/files) and see if you think it's that much uglier.  I don't...I think it improves things.  Well worth it for the hookpoint if you want to debug and find the moment something is created or assigned...

**Comment by hostilefork** [comment]
*(If I wasn't clear enough, I meant that function arguments will have VALUE_FLAG_STACK set on them as well.  They just won't have their reference FRAME! right immediately behind them.  It will take a few steps)*

**Comment by hostilefork** [comment]
Okay, I went ahead and merged this part.  Hopefully it won't cause you too much trouble.

I managed to clarify some things.  A valid cell for writing into will always have NODE_FLAG_CELL set, while a valid cell for reading from will have NODE_FLAG_VALID set.  That means that to "trash" a cell, you basically leave NODE_FLAG_CELL alone but remove NODE_FLAG_VALID.  This is simpler than it used to be, where trashes were some special flag on voids.

Then there are those two types of ENDs... the ones where they either have NODE_FLAG_CELL set on them (e.g. writable) or not.  But both have NODE_FLAG_VALID in all cases now, whether they are an implicit end or not.

Also, the macros for SET_BLANK or SET_TRUE etc. have been reduced a lot.  Hence so far, this change has been simplifying.  But give it a few commits and we'll see if that's still the case.  :-)

*(Actually, it's not yet looking all THAT bad.)*

**Pull request merged**
