### PR TITLE
Add platform Macintosh

### PR DESCRIPTION
**Pull request by iArnold**
Minor addition of platform 'Macintosh as osx is called in R3 console on my Mac.

### CODE REVIEW

**Comment by hostilefork** [comment]
> osx is called in R3 console on my Mac

Can you explain the context of this?  What does this impact?  Why is it happening?

Where is the source of the "Macintosh" word it is comparing with?  I assume it's this in %systems.r:

https://github.com/metaeducation/ren-c/blob/0d014aa68e2ce886a6d4d087fccbd89a3c76a928/make/tools/systems.r#L66

Is "Macintosh" correct with R3-Alpha?  Historical Rebol2?  Is this just a quirk in the rebmake stuff, that entered it wrong?

Are there other places where "OSX" is used?  Was make trying to be consistent with something else?

**Comment by iArnold** [comment]
This reference to 'Macintosh is also present in the generated r3. I will be happily reverting this change once the r3 program that comes with the download does not say 'Macintosh anymore and the generated r3 also says it is osx not 'Macintosh.

**Comment by iArnold** [comment]
Good point. Will take this into account.

**Comment by iArnold** [comment]
THIS ONE IS CLOSED.

**Pull request closed without merging**
