### PR TITLE
Include %mezz/ in source analysis checks

### PR DESCRIPTION
**Pull request by codebybrett**
Plus some comments.

### CODE REVIEW

**Comment by codebybrett** [comment]
Hm, I forgot to add checking of the tests. But as I'm in a closing café on a mobile connection I'll add this later.

**Comment by codebybrett** [comment]
When I wrote this script originally I wrote it to avoid a read folder bug in Linux R3-Alpha, hence the fixed paths and hence why %mezz/ was not included in the source analysis checks.

It occurs to me that avoiding said bug is probably not necessary now, if I can assume that the tests will only be run against the newly built ren-c, in which case I can use a recursive read strategy for the files to be checked instead of hard-coded paths.

@hostilefork  is that an assumption I can make?  Also if going the recursive read, what are the paths now that should or should not be included?  There is a whitelisted list for exclusions already, so I could modify that to include folder path checks instead of simple file path checks.

%tests/ is a peer folder to %src/ so a little extra work is needed for that also.

**Comment by hostilefork** [comment]
This looks like it needs some kind of rebase, a PR shouldn't have already-committed-commits in it... ("PROBE passes through value in C++...", "Make Is_Value_Managed() tolerate...")

**Comment by codebybrett** [comment]
@hostilefork I think this does what you asked for.  It now does a recursive read of %src/ and %tests/ - ignores "tmp-" files.  Thus, it picks up a lot more files.

**Comment by codebybrett** [comment]
Ugh.  I've pulled in some recent changes to the branch.  I'll close this and create a clean PR.

**Pull request closed without merging**
