### PR TITLE
Build system: allow multiple build folders

### PR DESCRIPTION
**Pull request by giuliolunati**
You can invoke make.r from outside,
all generated files go under current dir.
So you can keep multiple build dirs.

(This commit moves tools files to %make/tools)

### CODE REVIEW

**Comment by codebybrett** [comment]
I tried:

    C:\Projects\Public\test>..\ren-c\make\r3-make.exe ../ren-c/make/make.r CONFIG=../0.myconfig.r DEBUG=asserts OPTIMIZE=2

This worked in creating an objs/ folder in my current directory test. But then it couldn't find the objs:

    mingw32-gcc: error: objs\a-constants.obj: No such file or directory
    mingw32-gcc: error: objs\a-globals.obj: No such file or directory

I wonder if the output directory could be a build argument that defaults to current directory if not given.

References in source-tools.reb are broken too. Because %tests/source-tools.reb shares the same parsers with the make process, maybe the source parsing tools should be moved to %scripts/source/ or %tools/ so that it is more obvious that they might be used in more than one place and perhaps interactively.

As an aside, probably as a separate PR, source-tools.reb itself could be moved to a %tools/ folder not under %make/ because it and other scripts for analysing the source interactively might be useful. If this happens the reference in %test/source/analysis.test.reb will have to be updated.

**Comment by giuliolunati** [comment]
@codebybrett: "I wonder if the output directory could be a build argument that defaults to current directory if not given." -- I tried that, but warn: if you want a working makefile, it must be in current dir.

**Comment by giuliolunati** [comment]
@codebybrett: could you try `... make.r ... clean prep makefile, then share the generated makefile?

**Comment by giuliolunati** [comment]
@codebybrett -- last commit fixes source-tools.reb, for now

**Comment by codebybrett** [comment]
@giuliolunati Just re-tried with an empty directory. Looks like I missed some earlier errors last time, sorry about that.

    ext: Debugger: [Debugger ]
    Dynamic extensions
    Running: rmdir /S /Q objs
    Running: rmdir /S /Q prep
    The system cannot find the file specified.
    Running: del r3.exe
    Could Not Find C:\Projects\Public\test\r3.exe
    Running: r3-make.exe -qs /C/Projects/Public/ren-c/make/tools/make-natives.r
    'r3-make.exe' is not recognized as an internal or external command,
    operable program or batch file.
    Running: r3-make.exe -qs /C/Projects/Public/ren-c/make/tools/make-headers.r
    'r3-make.exe' is not recognized as an internal or external command,
    operable program or batch file.

**Comment by codebybrett** [comment]
Scrub that. Something is different this time. I'm not sure why.

**Comment by giuliolunati** [comment]
@codebybrett thank you! ;-)

**Comment by codebybrett** [comment]
I prepared by deleting my clone and pulled it down again.

Then for first test within ren-c/make I did:

    C:\Projects\Public\ren-c\make>r3-make.exe make.r CONFIG=../../0.myconfig.r DEBUG=asserts OPTIMIZE=2

This built %make/r3.exe successfully and gave me these folders: %make/objs/ %make/prep/

I then deleted: %make/objs/ %make/prep/ %make/r3.exe and changed to empty directory (test) and run:

    C:\Projects\Public\test>..\ren-c\make\r3-make.exe ../ren-c/make/make.r CONFIG=../0.myconfig.r DEBUG=asserts OPTIMIZE=2

But there is no path to r3-make.exe so I got a lot of errors of:

    Running: r3-make.exe -qs /C/Projects/Public/ren-c/make/tools/make-natives.r
    'r3-make.exe' is not recognized as an internal or external command,
    operable program or batch file.

Modifying make.r as follows:

    reb-tool: make rebmake/var-class [
        name: {REBOL_TOOL}
        value: really file! any [
            join-of make-dir user-config/rebol-tool
            system/options/boot
            to-file unspaced [{./r3-make} rebmake/target-platform/exe-suffix]
        ]
    ]

Built successfullly with no changes in ren-c/ as far as I could tell:

    Directory of C:\Projects\Public\test

    26/01/2018  12:21 PM    <DIR>          .
    26/01/2018  12:21 PM    <DIR>          ..
    26/01/2018  12:20 PM    <DIR>          objs
    26/01/2018  12:17 PM    <DIR>          prep
    26/01/2018  12:21 PM         3,099,154 r3.exe
                1 File(s)      3,099,154 bytes
                4 Dir(s)  175,996,841,984 bytes free

For this scenario, there is no need for an output directory argument, so ignore my earlier comment about that.

**Comment by giuliolunati** [comment]
@codebybrett thank you for testing! -- I think the `rebol-tool` option must be deprecated, `system/options/boot` should always work fine. @hostilefork ?

**Comment by hostilefork** [comment]
Great stuff @giuliolunati, and thanks @codebybrett for being a guinea pig.  :-)

> I think the rebol-tool option must be deprecated, system/options/boot should always work fine.

In practice for the systems we are using today, it should probably work.  But when it comes to new platforms, there is no guaranteed way to detect the executable.  It's an inexact science:

https://stackoverflow.com/a/1024937/211160

Note in particular that argv[0] is only a convention that some shells obey, but when processes are spawned anything can be put there:

https://stackoverflow.com/a/2051035/211160

So I'd suggest making a note about this on the REBOL_TOOL option, in case anyone wonders why it is there.

**Pull request merged**
