### PR TITLE
Update prot-http.r

### PR DESCRIPTION
**Pull request by gchiu**
add Graham's patches to allow the use of a headers word in the write dialect, and to return the location as arg2 in a redirect

### CODE REVIEW

**Comment by codebybrett** [comment]
I note that the whole protocol needs review/cleanup, so I'll limit comments to how interpretation of Write's value dialect has changed:

* HEADERS is used to make info available in DEBUG, couldn't info (line 305) be made available
unconditionally therefore not requiring the HEADERS keyword? If it has to be conditional I'm
not sure that HEADERS is the right keyword, to me it has the sense of setting headers not asking
for them.
* Adding word! to specify http method seems ok.

**Comment by gchiu** [comment]
to reduce cognitive loading, I just used the headers word from the rebol2
read/custom http dialect

If you always make the info available, then we're pushing extra bits around
that we don't need mostly.

On 8 October 2015 at 13:52, Brett Handley <notifications@github.com> wrote:

> I note that the whole protocol needs review/cleanup, so I'll limit
> comments to how interpretation of Write's value dialect has changed:
>
>    - HEADERS is used to make info available in DEBUG, couldn't info (line
>    305) be made available unconditionally therefore not requiring the HEADERS
>    keyword? If it has to be conditional I'm not sure that HEADERS is the right
>    keyword, to me it has the sense of setting headers not asking for them.
>    - Adding word! to specify http method seems ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/metaeducation/ren-c/pull/113#issuecomment-146384815>.
>



-- 
Graham Chiu

**Comment by gchiu** [comment]
The first make-http-error: should be removed.  It was the original version which I rewrote after it.

**Comment by hostilefork** [comment]
Per our discussion, the error-objects probably needs a better solution.

But integrated (minus the first error) to prevent holdups, as there are likely other issues to be resolved.

https://github.com/metaeducation/ren-c/commit/d8af94587a0bf9e2731ca449b14248a5a1c0bf2d

**Pull request closed without merging**
