### PR TITLE
Console banner changes

### PR DESCRIPTION
**Pull request by draegtun**
Added following to banner message on Console start:

  **    Resources: system/options/resources
  **    Console:   system/console/name

Console name can be one of four "states":

    "default"  - Not loaded Skin-file script
    "loaded"   - Skin-file script run but system/console not updated
    "updated"  - Skin-file script run and system/console updated
    "error"    - Skin-file produced an error

Console name can be changed by the console! object returned by %console-skin.reb (Skin-file)

The command-line --verbose switch will show more detailed Console skinning messages.

NB. Above replaces original Console skinning messages.  See comments here: https://github.com/metaeducation/ren-c/commit/012c4ae6c9ec2187cbad777fe58779996f6673fc

### CODE REVIEW

**Comment by draegtun** [comment]
@gchiu - This PR also includes two bug squashes....

* If HOME env variables are blank then `system/options/home` was set to current-path.  Now returns `_`

* Console would error if `%console-skin.reb` didn't return an object!

Please check all good for you.

**Comment by hostilefork** [comment]
We've discussed the growing size of the banner, and whether this thing that most people skip over is prudent to be giving so much screen real estate on every startup...

Might it be that we go with suggesting the existence of **about** and **help**, and reduce the amount of information you see to just a hint of where to find it?  --verbose could do ABOUT by default.

**Comment by draegtun** [comment]
@hostilefork @gchiu 

How about this on plain `r3`

    Rebol 3 (Ren/C branch) Version 2.102.0.2.5

    Welcome to the Rebol console.  For more information please type in the commands below:

      HELP  - For starting information
      ABOUT - Information about this build
      NOTES - Important notes about this version

    >>

So first line is like a small one-line banner followed by intro.  If wanted to see full banner instead of this single-line version on start-up then use `r3 --about`.

And to skip the banner/intro completely then `r3 --quiet`

      >>

Thoughts?  Any changes to text?

Also on my radar is updating `HELP` content and adding a `help console` post writing up docs.

**Comment by gchiu** [comment]
We sort of continued the rebol2 history of showing all the activated modules etc, but I think I like the clean look better.  We can get the information from __about__

**Comment by gchiu** [comment]
Rebol 3 (Ren/C branch) Version 2.102.0.2.5

  HELP  - For starting information
  ABOUT - Information about this build

**Pull request merged**
