### PR TITLE
Unify semantics of GET-PATH + PICK*, and SET-PATH! + POKE

### PR DESCRIPTION
**Pull request by hostilefork**
There was significant common code between PICK and POKE and the
GET-PATH! and SET-PATH! operations, with minor differences between
the operations that weren't clearly intentional.

It is not possible to write path processing in terms of PICK and POKE
such that `a/b/c: d` would act as `poke (pick (pick a 'b) 'c) d`.
The reason for this is that the result of the picks is a value taken
out of a position, which no longer has a relationship to the location
from which it was taken.

However, it is mostly possible to write PICK and POKE in terms of path
processing.  The exception is if PICK and POKE are operations used
as port actions, because there is no way for ports to override path
dispatch...and if they did, they would lose the ability to behave as
objects.  (Note: this points to a bigger issue about ports not being
able to serve two masters, as many actions that apply to objects could
be interesting when defining specialized port actions, e.g. APPEND)

This commit forces PICK and POKE through the same code path used by
path getting and setting.  That code is known to be needing attention
to improve it, but this helps ensure that the improvement can benefit
(and be checked) by both operating forms.

In order to work around the current PORT! issue, the SYM_PICK_P and
SYM_POKE symbols are sent explicitly to the port actor.

The most significant impact of this commit that people should notice
is that `blk/picker` will error if the picker does not pick out of
a block, just as `obj/picker` would do if there was nothing picked
out of an object (or `var` would do if there was no variable).  One has
to use `:blk/picker`.  Examining the affected code shows that it is
an apparent benefit to need to distinguish whether you expect a value
or not, but that the hard-to-handle nature of void means one often
has to say `to-value :blk/picker` or other mitigation to get a blank.
This suggests a need to investigate alternatives, e.g. if @blk/picker
could be a request for a void on absence, with :blk/picker being a
request for a blank.

### CODE REVIEW

**Comment by hostilefork** [comment]
Path dispatch is clumsy, but leaning on it harder is a good way to pressure it to get better.  :-/  As with everything else, it's under quite a lot more control than in R3-Alpha...so it can be changed.  Will be easier to reason about without having parallel code for PICK and POKE.

In actually, PICK and POKE weren't used all that unconventionally, relative to pathing.  **pick [a b c] 'a** didn't give you back **b** before, even though **blk: [a b c] | blk/a** would.  Yet like pathing, it had a "polymorphism" to it... **pick [a b c] true** would be `a` and **pick [a b c] false** would be `b`, and types other than blocks gave it meaning--generally equated with pathing.

So what this really did was make them a bit weirder.  **pick %foo %bar** gives you `%foo/bar` as does **pick %foo 'bar**.  While it's weird, it's not so much weirder than it was...how is saying that's what you get from "picking" different from "pathing"?  There could be some type checking that made picking a subset of pathing operations, but I don't see any reason why it would need to be "different". 

Also **file: %foo | file/1** giving back `#"f"` instead of `%foo/1`, which given the fact that paths already treated integers differently, seems more useful to me.  The polymorphism that PICK and pathing has with integers seems to be indexing, not other interpretations.

Anyway, with all the other things to do, I don't see why "I have some value X, use Y polymorphically to get me something out of it" needs to have more than one definition.  So this seems like a good step to me.

**Comment by giuliolunati** [comment]
I agree. The more uniform behavior, the better.

*Side note:* `pick` and `poke` can be user customized, so I'd like to be for paths. E.g. an "hook": `x/y` calls `path-hook x y` and the user can redefine `path-hook` (so 3/4 can result in 0.75 or in a fraction object...)

**Comment by hostilefork** [comment]
@giuliolunati A problem with a path hook is that since "pathing" itself does not have a binding, there'd be no way to resolve in the system which notion of pathing to use.  Any change you would make to it would take effect globally, affecting all code.  So if you changed the interpretation of something the mezzanine relied upon it would break.

To bypass that problem, you'd have to have a way to bind paths to a kind of "virtual **/** operator", so that they could carry the version of the "operator" they meant with them.

I'm beginning some research with this, to see how to make **a: 20 | b: 10 | a / b** return 2, while **[a b c] / b** returns `c`.  It's experimental and relies upon the new infix developments.  But as a start, it would at least allow your code to use its own version of **/** while not disrupting those with other bindings.  Just an experiment, but I'll keep you posted!

**Comment by hostilefork** [comment]
After addressing the idea that plain GET can help pick up slack for the tolerant form of pathing (that used to exist in blocks) this is rebased and merged as:

https://github.com/metaeducation/ren-c/commit/10b3f639eabdca1e4a071fa2a173aeaa6aeee4b4

**Pull request closed without merging**
