### PR TITLE
Obsd build -  binary for OpenBSD x64 against commit 8994d23 

### PR DESCRIPTION
**Pull request by lkppo**
Build the binary for OpenBSD x64 against commit 8994d23

### CODE REVIEW

**Comment by hostilefork** [comment]
So I've now verified that this works, and gotten a successful compile out of it!  Thanks for the initiative...I will look into the ENSURE bug.  Hopefully a clean build works for you--it may be that something odd that has happened along the way in your explorations put a stray file in there that's messing things up (?)

**RE: this PR:** Having binaries committed in the GitHub is not a particularly "clean" thing and I don't know that I like it.  I wasn't the one that made that decision.  It was something Shixin did for expedience.

We now have an S3 instance that we depend on for our builds, and so the availability of that is assumed.  We can host bootstrap builds there.  Then we need some kind of easy way of telling people where to get them, ideally giving them a precise link for their platform.

Several things have changed since rather old decisions were made.  For one thing, we can do "out-of-source" builds, where you can have your build products in any directory.  This means we can put a makefile in the root directory that only instructs you where to find the bootstrap EXE and what things to type in order to get it to build in the `make` .

So I think what I'd like to do is use the addition of a new build as a provocation to move to a new model that doesn't put the bootstrap EXEs into GitHub.

**Comment by lkppo** [comment]
maybe my first build used a commit half broken that can build but is not working with some rebol code.

I first prepared a makefile and objs / prrp folders on Windows, changed \ to / in the makefile, uploaded on OBSD and compiled. I will give you the exact command to generate the first build.

I'm also against this practice of storing the byproduct of a build (binary, docs...) in a CVS, but a storage is needed for the byproduct somewhere else. So go for the right way if you could give me instructions.

**Comment by hostilefork** [comment]
> I'm also against this practice of storing the byproduct of a build (binary, docs...) in a CVS,

https://github.com/metaeducation/ren-c/issues/969

**Comment by hostilefork** [comment]
BSD binary now downloadable from S3.  The `prebuilt` directory is in the .gitignore (except for the README.md which is not ignored).  It is premade to encourage a standard location for storing bootstrap builds, but also as an added documentation point:

https://github.com/metaeducation/ren-c/tree/master/prebuilt

**Comment by lkppo** [comment]
Thanks. A good thing done.

**Pull request closed without merging**
