### PR TITLE
Add Android5 (0.13.2) to Travis builds

### PR DESCRIPTION
**Pull request by giuliolunati**
1. FFI is disabled
   because libffi should be compiled with -f PIC
2. TCC is disabled
   because I'm lazy

### CODE REVIEW

**Comment by hostilefork** [comment]
Great news...!  🥇 

We have too many builds, so I'd like the Android build to take over some of the random build switch permutation.  Maybe we kill builds 2 (64-bit linux, C with asserts) and 8 (64-bit windows, C++ with no debug).

(I actually don't think those builds are showing us errors we aren't finding in the rest... and a non-debug C++ build generally isn't going to be any different, because all the C++-isms are basically under an `#if !defined(NDEBUG)` anyway.)

But regardless, it's good to keep things shaken up, so if you could Android debug and release builds cover these two cases that will keep the total number of builds from getting any larger!

**Comment by hostilefork** [comment]
@zsx Well, we won't want FFI with emscripten, which @giuliolunati is also looking at.  And that won't usually want HTTP, TLS, BMP, PNG, etc. either (though I guess if you're building to load into Node.JS you can't assume you have image encoding and decoding, etc.)

I feel like we need to set up a build spec, a little Rebol-formatted file which feeds into the makefile generation process.  I guess we can go with a committed file `build-options.reb.default` in the make directory, which a user can choose to copy and edit and then say they overrode it.  Maybe just a better direction than trying to fit everything into a command line parameter to make-make....

**Comment by zsx** [comment]
@hostilefork by saying explicitly set, I meant explicitly setting it to "no" or "dynamic", or any proper value. I just want a central place to find which platform has what feature.

**Comment by giuliolunati** [comment]
Ok, I'll do
I'd like FFI also for Android, but I need your help:
1) how to cross-compile libffi?
2) how to set -f pic?

Il 12/mag/2017 02:55, "Shixin Zeng" <notifications@github.com> ha scritto:

*@zsx* commented on this pull request.

Looks good, but I would like FFI to be explicitly set for every platform in
the matrix.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/metaeducation/ren-c/pull/503#pullrequestreview-37734480>,
or mute the thread

**Comment by giuliolunati** [comment]
Ok, I'll do

Il 12/mag/2017 01:20, "Brian Dickens" <notifications@github.com> ha scritto:

**Pull request merged**
