### PR TITLE
New test format

### PR DESCRIPTION
**Pull request by codebybrett**
This commit changes encoding of individual test vectors to GROUP! and repurposes BLOCK! to be a containing test group.
Bug references previously encoded in comments and in ISSUE! are now consistently encoded as an ISSUE! that begins a test group.
Flags are now encoded as TAG!

The conversion code is temporarily left built-in to the test scripts so that developers can upgrade their own code bases.
The test parser has been upgraded to emit token types for precision, documentation and in case further work is to be done on it.

### CODE REVIEW

**Comment by hostilefork** [comment]
I merged it and all tests passing, looks good!

Since you've got the conversion all running, I guess right now would be the best time for us to think about any potential tweaks.  Your tests here were the motivator, so I'd like to get the ones that work in and raise the others as issues:

https://github.com/codebybrett/reb/blob/master/test/dates.test.reb

For your "setup" code you just use an ordinary BLOCK! (which would be a GROUP!) and put "true" at the end of it.  Which works, but it feels like there should be another way of saying that.

I pointed out in chat that there is this the old, common pattern of doing some setup and then testing a number of conditions:

    [ ;-- #whatever, NOTES
        foo: func [...] [...]
        more-setup-code
        did all [
            [...] = foo ...
            [...] = foo ...
        ]
    ]

If one of those conditions returns false, you have to manually go in and see which one.  So I thought it better to divide this where it could indicate which failed.  Then I suggested ELIDE instead of the true at the end of "setup code".

    [#whatever {Notes}
        elide (
            foo: func [...] [...]
            more-setup-code
        )
        ([...] = foo ...)
        ([...] = foo ...)
    ]

It makes me wonder if we should use some other kind of divider as a signal, then just not use those dividers in the tests?  :-/

    [
        #whatever {Notes}
        ---
        foo: func [...] [...]
        more-setup-code
        ---
        (foo [1 2 3] = 1)
        (capture = [1 2 3])
    ]

Of course it could be `-->` and `<--` or some other choice, or `===` and `---`. 

This kind of thing would go a little more in the direction of Red's tests without going quite all the way there.  I do like the BLOCK! and the GROUP!s, and the ability to put GROUP!s on their own outside blocks.  Red's tests are rather noisy to look at.

**Comment by codebybrett** [comment]
If no-one is objecting to the change my preference is to not defer this commit for a few reasons.  Since any proposed setup code inside the BLOCK! is optional, catering for setup shouldn't change the existing conversion.  I don't think the conversion can do much more and delaying may cause re-work. Time-wise, I spent quite a while to dot the i's and cross the t's on this conversion so I'm planning on putting this aside right now to work on stuff I've neglected recently.

I realise the point of this excercise is to get added value from grouped tests, but I think this should be a separate phase and perhaps it might be good to let these changes to settle in a bit, some time with them may make things clearer about what would be nice.

I'm unsure what would constitute a decent setup format.  Maybe just a BLOCK! before the first GROUP!, or put a keyword "context" before it  - "here is the context for these tests". 

    [
        #whatever {Notes}
        context [
            foo: func [...] [...]
            more-setup-code
        ]
        ([...] = foo ...)
        ([...] = foo ...)
    ]

Presumably any setup will be shared/mutable between the tests, rather than re-setup fresh for each test. Or perhaps that's a different keyword.

**Comment by hostilefork** [comment]
Your preference is my preference.  :-)  Okay, it's done...thanks, on we go!

**Comment by hostilefork** [comment]
I know you've got other things to do, but... I'm sure you don't want to miss out on [trying CONCOCT](https://trello.com/c/ko89tF2Y/)!

    >> concoct (()) [(1 + 2) ((1 + 2))]
    == [(1 + 2) 3]

    >> concoct [] quote ((1 + 2) [3 + 4] (5 + 6))
    == ((1 + 2) 7 (5 + 6))

    >> concoct [[]] 'a/(b)/[[1 + 2]]/[c]/d
    == a/(b)/3/[c]/d

*(Also it would really help if people could get in some basic tests now that [Latin-1 Nowhere](https://github.com/metaeducation/ren-c/pull/773) is committed...)*

Tests going well so far... just got to figure out how to run them in "isolated environments" :-/

**Pull request merged**
