### PR TITLE
Fileheaders 201603

### PR DESCRIPTION
**Pull request by codebybrett**
This updates the file headers to a new format to include rebol loadable metadata  and modifies the parser to accept the new format.

### CODE REVIEW

**Comment by codebybrett** [comment]
Odd, it builds on my windows machine but not travis. Looking into it.

**Comment by codebybrett** [comment]
Odd, it builds on my windows machine but not travis. Looking into it.

**Comment by codebybrett** [comment]
Odd, it builds on my windows machine but not travis. Looking into it.

**Comment by codebybrett** [comment]
I cannot remember if Atronix has confirmed that it is only their copyright (not Rebol Tech's) on these two files (because I removed the RT copyright notice on the basis that it looked like it was Atronix's work):

    %src/core/p-signal.c
    %src/os/linux/dev-signal.c

Other than that, I think the conversion is done.

**Comment by hostilefork** [comment]
All looks great to me...thanks for taking on such a tedious-but-necessary task!

**Pull request merged**
