### PR TITLE
Command-line option improvements

### PR DESCRIPTION
**Pull request by draegtun**
* Replaced FAIL with DIE for all other command-line switches (see PR #501)

      ./r3 +s
      Startup encountered an error!
      ** SECURE is disabled (never finished for R3-Alpha)

* Replaced FAIL with DIE in all (two) other cases in host-start (boot-embedded)

* Now dies when command-line option is missing a parameter:

      $ ./r3 --resources
      Startup encountered an error!
      ** RESOURCES parameter missing

* Fixed unknown command-line option catch.  Now also dies:

      ./r3 --foo
      Startup encountered an error!
      ** Unknown command line option: --foo
      !! For a full list of command-line options use:  --help

* USAGE (--help) content brought up-to-date

Along with some other minor fixes I hope above now catches all Command-line errors in a graceful way.

@hostilefork - Obviously even more could be done (see parameter checking).  But that's best left to the future command-line processing module.

### CODE REVIEW

**Comment by hostilefork** [comment]
Looks good to me.  I guess one question to ask is how much loyalty to Rebol2 command line switches is necessary, if there's any reason to change it to some drastically new or better system and just have a translating launch script for people who need compatibility.  Depends on if there's some vast improvement to be made.

**Comment by draegtun** [comment]
@hostilefork - This is certainly something we can look in future especially when CLI parsing module is available (for general use & within Rebol start-up).  One thing I do have to say is that the switch options in Rebol are so much cleaner and intuitive compared to Perl, Python & Ruby (just do `<lang> --help` and see the difference!)

**Comment by gchiu** [comment]
BTW, this was pointed out in chat https://github.com/rebol/rebol-issues/issues/2228 in case this has been forgotten

**Comment by draegtun** [comment]
@gchiu - Thanks for above issue (list).   Will look into it and see what can be done.

**Pull request merged**
