### PR TITLE
Fix source scripts

### PR DESCRIPTION
**Pull request by codebybrett**
This resolves a bug for source analysis tests, but more importantly removes duplication of functions and add some other improvements including some tests for functions the build depends upon.

### CODE REVIEW

**Comment by codebybrett** [comment]
An argument error inside DECODE-LINES was interpreted by the parser to skip function prototypes during source analysis tests (due to a duplicate DECODE-LINES in that scenario).

**Comment by hostilefork** [comment]
Great!  I get one of the text line tests failing (Linux)

    [quote "**^/**^/**^/" = encode-lines copy {^/^/} {**} {  }] "failed"

The result I'm getting for that is:

    >> mold encode-lines copy {^/^/} {**} {  }
    == {{**
    **  
    **
    }}

Now just to fix all those id-mismatch errors.  :-/  However, the ones in the %a-lib.c for the API were on purpose, those names really are supposed to be missing the RL_ prefix for the comment block.  That is checked by the build process itself.  If you wanted a simple check you might...right before a failure...see if adding RL_ to the beginning of any comment name would make it the function name, and that's probably good enough (vs. having to get into the specifics of checking anything else, that's already done).

**Comment by codebybrett** [comment]
Sorry missed the failing test, haven't got used to putting glasses on. Incidentally the test failure total seems to be out by 3, so I didn't trust it. Latest commit should fix the failing test.

**Comment by codebybrett** [comment]
RL_ workaround done.

**Comment by hostilefork** [comment]
All right then, all seems fixed up now!  Merged and rebased...

> Incidentally the test failure total seems to be out by 3, so I didn't trust it.

When draegtun added those 3 tests I wasn't building on Windows, and so I didn't notice until some time later when I did...and was too in the middle of whatever I was doing to look into it.  Then I got used to "oh, Windows just always has 3 fail, someone else who cares about whatever is wrong on Windows will fix it."

That's pretty lame of me.  So I fixed it:

https://github.com/metaeducation/ren-c/commit/d6acd3619c02d6beabb7ddf2a9738cd20fe3b1ad

Now, 0 errors!

**Comment by codebybrett** [comment]
Ah thank you.

**Pull request closed without merging**
